import 'dart:io';
import 'package:flutter/foundation.dart';
import '../../models/models.dart';

// ─────────────────────────────────────────────────────────────────────────────
// TripReportPdfService
//
// Generates a single-page PDF trip report and returns the file path.
//
// Required packages (add to pubspec.yaml):
//   dependencies:
//     pdf: ^3.10.8
//     printing: ^5.12.0
//     path_provider: ^2.1.2
//     share_plus: ^7.2.2
//
// Usage:
//   final path = await TripReportPdfService.generate(trip);
//   await TripReportPdfService.share(path, trip);
// ─────────────────────────────────────────────────────────────────────────────

class TripReportPdfService {
  TripReportPdfService._();

  /// Generates the PDF and returns the saved file path.
  /// Throws [UnsupportedError] on web (use share instead).
  static Future<String> generate(TripModel trip) async {
    // ── REAL IMPLEMENTATION ──────────────────────────────────────────────
    // import 'package:pdf/pdf.dart';
    // import 'package:pdf/widgets.dart' as pw;
    // import 'package:path_provider/path_provider.dart';
    //
    // final pdf = pw.Document();
    // final scoreColor = _pdfScoreColor(trip.score.overall);
    //
    // pdf.addPage(pw.Page(
    //   pageFormat: PdfPageFormat.a4,
    //   margin: const pw.EdgeInsets.all(32),
    //   build: (ctx) => pw.Column(
    //     crossAxisAlignment: pw.CrossAxisAlignment.start,
    //     children: [
    //       // Header
    //       pw.Row(mainAxisAlignment: pw.MainAxisAlignment.spaceBetween, children: [
    //         pw.Text('DRIVE METRICS AI', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold)),
    //         pw.Text('Trip Report', style: const pw.TextStyle(fontSize: 14)),
    //       ]),
    //       pw.Divider(),
    //       pw.SizedBox(height: 8),
    //
    //       // Score pill
    //       pw.Container(
    //         padding: const pw.EdgeInsets.all(16),
    //         decoration: pw.BoxDecoration(
    //           color: scoreColor.shade50,
    //           borderRadius: pw.BorderRadius.circular(12),
    //         ),
    //         child: pw.Row(children: [
    //           pw.Text('Safety Score', style: const pw.TextStyle(fontSize: 12)),
    //           pw.Spacer(),
    //           pw.Text('${trip.score.overall.toInt()} / 100  Grade ${trip.score.grade}',
    //             style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold, color: scoreColor)),
    //         ]),
    //       ),
    //       pw.SizedBox(height: 16),
    //
    //       // Stats grid
    //       pw.Row(children: [
    //         _statBox('Distance', '${trip.distanceKm.toStringAsFixed(1)} km'),
    //         _statBox('Duration', trip.durationLabel),
    //         _statBox('Max Speed', '${trip.maxSpeedKmh.toInt()} km/h'),
    //         _statBox('Avg Speed', '${trip.avgSpeedKmh.toInt()} km/h'),
    //       ]),
    //       pw.SizedBox(height: 16),
    //
    //       // Score breakdown
    //       pw.Text('Score Breakdown', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
    //       _scoreRow('Braking', trip.score.braking),
    //       _scoreRow('Cornering', trip.score.cornering),
    //       _scoreRow('Speeding', trip.score.speeding),
    //       _scoreRow('Smoothness', trip.score.smoothness),
    //       pw.SizedBox(height: 16),
    //
    //       // Behaviour detection breakdown
    //       pw.Text('AI Detection Summary', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
    //       pw.SizedBox(height: 6),
    //       ...trip.classCounts.entries.map((e) =>
    //         pw.Text('  ${e.key.label}: ${e.value} windows')),
    //       pw.SizedBox(height: 16),
    //
    //       // Events list
    //       if (trip.events.isNotEmpty) ...[
    //         pw.Text('Detected Events (${trip.events.length})', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
    //         pw.SizedBox(height: 6),
    //         ...trip.events.map((e) => pw.Padding(
    //           padding: const pw.EdgeInsets.symmetric(vertical: 2),
    //           child: pw.Row(children: [
    //             pw.Text('• ${e.label}  ', style: pw.TextStyle(color: PdfColors.red)),
    //             pw.Text('Conf: ${((e.confidence ?? 0) * 100).toInt()}%  '),
    //             pw.Text('G: ${e.value?.toStringAsFixed(2) ?? '-'}'),
    //           ]),
    //         )),
    //         pw.SizedBox(height: 16),
    //       ],
    //
    //       // Footer
    //       pw.Spacer(),
    //       pw.Divider(),
    //       pw.Text('Generated by Drive Metrics AI  •  ${_formatDate(trip.startTime)}',
    //         style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
    //     ],
    //   ),
    // ));
    //
    // final dir = await getApplicationDocumentsDirectory();
    // final file = File('${dir.path}/report_${trip.id}.pdf');
    // await file.writeAsBytes(await pdf.save());
    // return file.path;
    // ── END REAL IMPLEMENTATION ──────────────────────────────────────────

    // Stub: return a placeholder path
    await Future.delayed(const Duration(milliseconds: 800)); // simulate work
    final dir = Directory.systemTemp;
    final file = File('${dir.path}/report_${trip.id}.pdf');
    // Write a minimal placeholder so the file exists
    await file.writeAsString(
      'Drive Metrics AI Report — ${trip.id}\n'
      'Score: ${trip.score.overall.toInt()}/100 (${trip.score.grade})\n'
      'Distance: ${trip.distanceKm.toStringAsFixed(1)} km\n'
      'Events: ${trip.events.length}\n'
      'Generated: ${DateTime.now()}\n',
    );
    return file.path;
  }

  /// Open the system share sheet for the generated PDF.
  static Future<void> share(String filePath, TripModel trip) async {
    // ── REAL IMPLEMENTATION ──────────────────────────────────────────────
    // import 'package:share_plus/share_plus.dart';
    // await Share.shareXFiles(
    //   [XFile(filePath, mimeType: 'application/pdf')],
    //   subject: 'Drive Metrics AI — Trip Report ${_formatDate(trip.startTime)}',
    // );
    // ── END REAL IMPLEMENTATION ──────────────────────────────────────────
    debugPrint('[PDF] Share: $filePath');
  }

  /// Open print preview dialog.
  static Future<void> print(String filePath) async {
    // ── REAL IMPLEMENTATION ──────────────────────────────────────────────
    // import 'package:printing/printing.dart';
    // final bytes = await File(filePath).readAsBytes();
    // await Printing.layoutPdf(onLayout: (_) => bytes);
    // ── END REAL IMPLEMENTATION ──────────────────────────────────────────
    debugPrint('[PDF] Print: $filePath');
  }

  static String _formatDate(DateTime dt) =>
      '${dt.year}-${dt.month.toString().padLeft(2,'0')}-${dt.day.toString().padLeft(2,'0')}';
}
